### ISSUE TITLE
constify_imm8! isn't compiling down to a single instruction

### ISSUE THREAD

**Issue by AdamNiederer** [rust-lang-nursery/stdsimd#47]
Adding `#[cfg_attr(test, assert_instr(pcmpestri))]` to `pub fn _mm_cmpestri(` in the sse42 module is causing a test failure. It's also happening for the as-of-yet unmerged `_mm256_round_pd` in the `avx` module.

```
---- x86::sse42::assert_instr__mm_cmpestri stdout ----
	disassembly for stdsimd::x86::sse42::_mm_cmpestri: 
	 0: push %rbp 
	 1: mov %rsp,%rbp 
	 2: xor %eax,%eax 
	 3: test %al,%al 
	 4: jne 22a15 <_ZN7stdsimd3x865sse4212_mm_cmpestri17h7ae9c893295f749dE+0x795> 
	 5: add $0x80,%dl 
	 6: movzbl %dl,%eax 
	 7: lea 0x98905(%rip),%rcx # baba0 <ref.3l+0x650> 
	 8: movslq (%rcx,%rax,4),%rax 
	 9: add %rcx,%rax 
	10: jmpq *%rax 
	11: mov %edi,%eax 
	12: mov %esi,%edx 
	13: vpcmpestri $0x80,%xmm1,%xmm0 
	14: jmpq 23181 <_ZN7stdsimd3x865sse4212_mm_cmpestri17h7ae9c893295f749dE+0xf01> 
	15: mov %edi,%eax 
	16: mov %esi,%edx 
	17: vpcmpestri $0x81,%xmm1,%xmm0 
	18: jmpq 23181 <_ZN7stdsimd3x865sse4212_mm_cmpestri17h7ae9c893295f749dE+0xf01> 
	19: mov %edi,%eax 
	20: mov %esi,%edx 
	21: vpcmpestri $0x82,%xmm1,%xmm0 
	22: jmpq 23181 <_ZN7stdsimd3x865sse4212_mm_cmpestri17h7ae9c893295f749dE+0xf01> 
	23: mov %edi,%eax 
	24: mov %esi,%edx 
	25: vpcmpestri $0x83,%xmm1,%xmm0 
	26: jmpq 23181 <_ZN7stdsimd3x865sse4212_mm_cmpestri17h7ae9c893295f749dE+0xf01> 
	27: mov %edi,%eax 
	28: mov %esi,%edx 
	29: vpcmpestri $0x84,%xmm1,%xmm0 
	30: jmpq 23181 <_ZN7stdsimd3x865sse4212_mm_cmpestri17h7ae9c893295f749dE+0xf01> 
	31: mov %edi,%eax 
	32: mov %esi,%edx 
	33: vpcmpestri $0x85,%xmm1,%xmm0 
        ...
	1037: nopw %cs:0x0(%rax,%rax,1) 
	1038: 
	1039: nop 
thread 'x86::sse42::assert_instr__mm_cmpestri' panicked at 'failed to find instruction `pcmpestri` in the disassembly', assert-instr/src/lib.rs:290:8
```

Ignoring the problem with LLVM widening instructions, it looks like the macro is generating an enormous switch/match statement rather than a single instruction. I'm assuming this isn't intended?

**Comment by alexcrichton** [comment]
I was wondering about this and I think [it may actually be correct](https://github.com/rust-lang-nursery/stdsimd/pull/43#issuecomment-332295065), we're just testing it incorrectly? Want to test out the testing strategy [in the last comment](https://github.com/rust-lang-nursery/stdsimd/pull/43#issuecomment-332335204)?

**Comment by AdamNiederer** [comment]
```rust
    #[cfg(test)]
    #[target_feature = "+sse4.2"]
    #[cfg_attr(test, assert_instr(pcmpestri))]
    fn _mm_cmpestri_instr(
        a: __m128i,
        la: i32,
        b: __m128i,
        lb: i32,
        imm8: i8,
    ) -> i32
    {
        sse42::_mm_cmpestri(a, la, b, lb, sse42::_SIDD_CMP_EQUAL_ORDERED)
    }
```
```
---- x86::sse42::tests::assert_instr__mm_cmpestri_instr stdout ----
	disassembly for stdsimd::x86::sse42::tests::_mm_cmpestri_instr: 
	 0: push %rbp 
	 1: mov %rsp,%rbp 
	 2: mov %edi,%eax 
	 3: mov %esi,%edx 
	 4: vpcmpestri $0xc,%xmm1,%xmm0 
	 5: mov %ecx,%eax 
	 6: pop %rbp 
	 7: retq 
	 8: nopw %cs:0x0(%rax,%rax,1) 
	 9: 
	10: nopl 0x0(%rax) 
thread 'x86::sse42::tests::assert_instr__mm_cmpestri_instr' panicked at 'failed to find instruction `pcmpestri` in the disassembly', assert-instr/src/lib.rs:290:8

```

Looks like that fixes it, thanks.

**Comment by alexcrichton** [comment]
Nice!
